version: "3"
services:
  identidock:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    networks:
      - webnet
    depends_on:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster:1.0
    networks:
      - webnet

  redis:
    image: redis
    networks:
      - webnet
networks:
  webnet:

